services:
    auth-server:
        image: vigneshperiasami/authserver:latest
        build:
            context: .
            platforms:
                - "linux/amd64"
            target: js-auth-server
        ports:
            - 3000:3000
        environment:
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
