
services:
    app-server:
        image: vigneshperiasami/travel-backend:latest
        build:
            context: .
            target: backend-server
            platforms:
                - "linux/amd64"
        ports:
            - 8089:8089
        environment:
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
